---
title: "Task19"
author: "Cole Hon"
date: "11/14/2022"
output:
html_document:
  keep_md: true
  code_folding: 'hide' 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(knitr)
library(downloader)
library(tidyverse)
library(USAboundaries)
library(USAboundariesData)
library(ggsflabel)
library(remotes)
library(devtools)
library(ggplot2)
library(maps)
library(leaflet)
```

```{r}
cities <- us_cities() 
states <- us_states()
county <- us_counties()
idahocounties <- us_counties(states = "ID")

no_alaskahawaii <- cities %>%
  filter(state_name != 'Alaska', state_name != 'Hawaii')
```

```{r}
top3pop <- no_alaskahawaii %>%
  group_by(state_name) %>%
  arrange(desc(population))
head(top3pop)
biggest_cities <- top3pop %>%
  slice(1:3)
head(biggest_cities)
biggest <- biggest_cities %>%
  slice(1:1)
middle <- biggest_cities %>%
  slice(2:2)
smallest <- biggest_cities %>%
  slice(3:3)
```


```{r}
leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = biggest,
                   radius = 7,
                   color = "darkblue",
                   stroke = FALSE,
                   fillOpacity = 1,
                   popup = ~city,
                   label = ~population) %>%
  addCircleMarkers(data = middle,
                   radius = 5,
                   color = "blue",
                   stroke = FALSE,
                   fillOpacity = 1,
                   popup = ~city,
                   label = ~population) %>%
  addCircleMarkers(data = smallest,
                   radius = 3,
                   color = "lightblue",
                   stroke = FALSE,
                   fillOpacity = 1,
                   popup = ~city,
                   label = ~population)
```




